Script started on Sat 27 Feb 2021 05:31:54 PM PST
]0;jsugijot@crystalcove:hw4[jsugijot@crystalcove hw4]$ make clean
rm -f *.o *.jpg PhotoLab_v3 PhotoLabTest edge.ppm sharpen.ppm posterize.ppm aging.ppm negative.ppm noise.ppm libfilter.a libFileIO.a
rm -f PhotoLab_v3
rm -f PhotoLabTest
]0;jsugijot@crystalcove:hw4[jsugijot@crystalcove hw4]$ make 
gcc -ansi -std=c99 -Wall -c -g PhotoLab_v3.c -o PhotoLab.o
gcc -ansi -std=c99 -Wall -c -g -DDEBUG FileIO.c -o FileIO.o
gcc -ansi -std=c99 -Wall -c -g Image.c -o Image.o
gcc -ansi -std=c99 -Wall -c -g DIPs.c -o DIPs.o
gcc -ansi -std=c99 -Wall -c -g Advanced.c -o Advanced.o
ar rc libfilter.a Advanced.o DIPs.o
ranlib libfilter.a
gcc -ansi -std=c99 -Wall -c -DDEBUG -g  Test.c -o Test.o
gcc -ansi -std=c99 -Wall PhotoLab.o FileIO.o Image.o Test.o -L. -lfilter -o PhotoLab_v3 -lm
gcc -ansi -std=c99 -Wall -c -DDEBUG -g  -c PhotoLab_v3.c -o PhotoLab_DEBUG.o
gcc -ansi -std=c99 -Wall PhotoLab_DEBUG.o FileIO.o Image.o Test.o -L. -lfilter -o PhotoLabTest -lm
]0;jsugijot@crystalcove:hw4[jsugijot@crystalcove hw4]$ ./PhotoLab_v3

-------------------------
 1: Load a PPM image
 2: Save image in PPM and JPEG format
 3: Run aging
 4: Run edge detection filter
 5: Run sharpen filter
 6: Run noise filter
 7: Run posterize filter
 8: Run negative filter
 9: Enlarge image
10: Create square (crop) image
11: Adjust brightness and contrast
22: Test all functions
99: Exit

-------------------------
Please make your choice: 22
drinks.ppm was read successfully!
original.ppm was saved successfully. 
original.jpg was stored for viewing. 
LoadImage & SaveImage tested!

drinks.ppm was read successfully!
aging.ppm was saved successfully. 
aging.jpg was stored for viewing. 
Aging tested!

drinks.ppm was read successfully!
sharpen.ppm was saved successfully. 
sharpen.jpg was stored for viewing. 
Sharpen tested!

drinks.ppm was read successfully!
edge.ppm was saved successfully. 
edge.jpg was stored for viewing. 
Edge tested!

drinks.ppm was read successfully!
noise.ppm was saved successfully. 
noise.jpg was stored for viewing. 
Noise tested!

drinks.ppm was read successfully!
posterize.ppm was saved successfully. 
posterize.jpg was stored for viewing. 
Posterization tested!

drinks.ppm was read successfully!
negative.ppm was saved successfully. 
negative.jpg was stored for viewing. 
Negative tested!

drinks.ppm was read successfully!
enlarge.ppm was saved successfully. 
enlarge.jpg was stored for viewing. 
Enlarge tested!

drinks.ppm was read successfully!
square.ppm was saved successfully. 
square.jpg was stored for viewing. 
Square tested!

drinks.ppm was read successfully!
brightnessandcontrast.ppm was saved successfully. 
brightnessandcontrast.jpg was stored for viewing. 
Brightness and Contrast tested!


-------------------------
 1: Load a PPM image
 2: Save image in PPM and JPEG format
 3: Run aging
 4: Run edge detection filter
 5: Run sharpen filter
 6: Run noise filter
 7: Run posterize filter
 8: Run negative filter
 9: Enlarge image
10: Create square (crop) image
11: Adjust brightness and contrast
22: Test all functions
99: Exit

-------------------------
Please make your choice: 99
You exit the program.
]0;jsugijot@crystalcove:hw4[jsugijot@crystalcove hw4]$ valgrind --leak-check=full ./PhotoLabTest
==972== Memcheck, a memory error detector
==972== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==972== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==972== Command: ./PhotoLabTest
==972== 
drinks.ppm was read successfully!
original.ppm was saved successfully. 
original.jpg was stored for viewing. 
LoadImage & SaveImage tested!

drinks.ppm was read successfully!
aging.ppm was saved successfully. 
aging.jpg was stored for viewing. 
Aging tested!

drinks.ppm was read successfully!
sharpen.ppm was saved successfully. 
sharpen.jpg was stored for viewing. 
Sharpen tested!

drinks.ppm was read successfully!
edge.ppm was saved successfully. 
edge.jpg was stored for viewing. 
Edge tested!

drinks.ppm was read successfully!
noise.ppm was saved successfully. 
noise.jpg was stored for viewing. 
Noise tested!

drinks.ppm was read successfully!
posterize.ppm was saved successfully. 
posterize.jpg was stored for viewing. 
Posterization tested!

drinks.ppm was read successfully!
negative.ppm was saved successfully. 
negative.jpg was stored for viewing. 
Negative tested!

drinks.ppm was read successfully!
enlarge.ppm was saved successfully. 
enlarge.jpg was stored for viewing. 
Enlarge tested!

drinks.ppm was read successfully!
square.ppm was saved successfully. 
square.jpg was stored for viewing. 
Square tested!

drinks.ppm was read successfully!
brightnessandcontrast.ppm was saved successfully. 
brightnessandcontrast.jpg was stored for viewing. 
Brightness and Contrast tested!

==972== 
==972== HEAP SUMMARY:
==972==     in use at exit: 0 bytes in 0 blocks
==972==   total heap usage: 76 allocs, 76 frees, 11,212,608 bytes allocated
==972== 
==972== All heap blocks were freed -- no leaks are possible
==972== 
==972== For counts of detected and suppressed errors, rerun with: -v
==972== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 8 from 6)
]0;jsugijot@crystalcove:hw4[jsugijot@crystalcove hw4]$ ex[K[Kmake clean
rm -f *.o *.jpg PhotoLab_v3 PhotoLabTest edge.ppm sharpen.ppm posterize.ppm aging.ppm negative.ppm noise.ppm libfilter.a libFileIO.a
rm -f PhotoLab_v3
rm -f PhotoLabTest
]0;jsugijot@crystalcove:hw4[jsugijot@crystalcove hw4]$ exit
exit

Script done on Sat 27 Feb 2021 05:34:04 PM PST
